### ISSUE TITLE
Is it possible to use Vidyard video link

### ISSUE THREAD

**Issue by JaydeepTank2** [bagabont/videogular-vimeo#1]
Hi,
is it possible  to use Vidyard video link in Videogular using Videogular-Vimeo and the URL is like (http://play.vidyard.com/oTsvMGB9ztAuFbVMsGLCRg) or have to create something like you have created?
Regards,
Jaydeep Tank

**Comment by bagabont** [comment]
Hi,
As for the plugin, unfortunately it does only what it says: allows videogular to play videos from video sources. I took a look at the vidyard API and from first glance it seems as they expose the iFrame player's API. However, in order to consume it you will have to create a separate plugin
Here are a couple of the links, I hope they help:

1) https://gist.github.com/jramsahai/1f0be24672c0b0da558d
2) https://www.vidyard.com/blog/trigger-video-playback-player-visibility/****

**Comment by JaydeepTank2** [comment]
Thanks! Momchil Marinow,

I will give it try.

Regards,
Jaydeep Tank
